# Generated by Django 4.1.3 on 2022-11-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("images", models.JSONField(blank=True, default=None, null=True)),
                (
                    "audio_url",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "video_url",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("explanation", models.TextField()),
                ("locale", models.CharField(max_length=200)),
                ("term", models.CharField(max_length=200)),
                (
                    "parent_term",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="music.term",
                    ),
                ),
            ],
        ),
    ]
